### ISSUE TITLE
Voice: custom stream support

### ISSUE THREAD

**Issue by nhooyr** [cronokirby/alchemy#40]
Presently, alchemy only plays audio from URL's supported by youtube-dl or from a file.

It should be possible to provide a custom stream to alchemy and have it play audio from that. I'm not sure what the API should look like though.

**Comment by cronokirby** [comment]
https://github.com/cronokirby/alchemy/commit/769cd07c0f7ad3400c4dd27956c5c65b25775972 fixes this.
`play_iodata/3` now takes in either iodata, or a stream of iodata.
