### ISSUE TITLE
How to use reactions?

### ISSUE THREAD

**Issue by Zesky665** [cronokirby/alchemy#48]
I was looking though the code and couldn't figure out how to add reactions to messages. How do I add a reaction or multiple to a message.

**Comment by cronokirby** [comment]
You'll find stuff much quicker in the docs than in the code: <https://hexdocs.pm/discord_alchemy/0.6.0/Alchemy.Client.html#add_reaction/2>

**Comment by Zesky665** [comment]
Wow, thanks, how did I manage to miss it :p
