### ISSUE TITLE
Issue with Voice

### ISSUE THREAD

**Issue by Zesky665** [cronokirby/alchemy#50]
I've tried to implement the voice example from the introduction. When using the play(url) command, I get the following error. 

`11:56:45.995 [error] Task #PID<0.256.0> started from #PID<0.242.0> terminating
** (ArgumentError) unknown registry: Registry.Voice
    (elixir) lib/registry.ex:758: Registry.key_info!/1
    (elixir) lib/registry.ex:419: Registry.lookup/2
    (alchemy) lib/Structs/Voice/voice.ex:108: Alchemy.Voice.join/3
    (gerard) lib/dj.ex:34: Gerard.DJ.join_voice/1
    (elixir) lib/task/supervised.ex:85: Task.Supervised.do_apply/2
    (stdlib) proc_lib.erl:247: :proc_lib.init_p_do_apply/3
Function: &Gerard.DJ.join_voice/1
`

**Comment by cronokirby** [comment]
Did you correctly specify the the paths to ffmpeg and youtube_dl?
Not doing that would cause this

**Comment by Zesky665** [comment]
I'll check. Does the path have to lead to the executable file for ffmpeg or youtube_dl?

Update: It was a typo on my end :P
