### ISSUE TITLE
How to specify voice channels

### ISSUE THREAD

**Issue by Zesky665** [cronokirby/alchemy#51]
I've tried and somewhat successfully implemented the example from the introduction.  The issue I've noticed is that there doesn't seem to be a way to get the id of a voice channel through the code itself. The comment in the example mentions that the bot will join the default voice channel, which isn't what has happened on my end.

**Comment by cronokirby** [comment]
Example:  
```elixir
{:ok, guild} = Cogs.guild()
some_voice_channel = Enum.find(guild.channels, &match?(%{type: :voice}, &1))
```

Perhaps we should replace the example in the readme with something like this, since the default channel will no longer work...

**Comment by Zesky665** [comment]
I'll see if I can do that and add some more examples. I'm currently working on a bot with this library that has a lot of basic features, perhaps we can link to it as an  example.
