### ISSUE TITLE
Channel Categories

### ISSUE THREAD

**Issue by lun-4** [cronokirby/alchemy#54]
Every channel object(in a guild) *can have* a `parent_id` field(it should be `nil` when no category), it is a snowflake that points to another channel(the channel category, type 4), the category has its own name and permission overwrites which *can* be synced to the category's childs.

Note: In theory, categories can have category childs, but the UI doesn't allow that 🤷‍

We could add a `Alchemy.Category.t` where it could have functions like a `get_childs(category_id) :: [Alchemy.Channel.t]`.

**Comment by cronokirby** [comment]
Thinking of splitting the channel type into 5 types (one for each id) instead of having this weird spec of keys that may or may not be there

**Comment by lun-4** [comment]
It would be really nice! checking for the actual type instead of missing keys sounds way better

**Comment by cronokirby** [comment]
New pr splits up the channel types, feel free to raise issues / pr for utility functions or modifications related to this
