### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by reallinfo** [cronokirby/alchemy#59]
Hello! I am a graphic designer. I want to contribute to alchemy. Do you want me to design a logo for the alchemy?

**Comment by cronokirby** [comment]
feel free to submit a PR, I guess

**Comment by reallinfo** [comment]
I designed a logo from the bubbles to represent the alchemy. How is these? Also, I can change the color of the bubbles. or I can send a pr.

![alchemy](https://user-images.githubusercontent.com/36298335/40626762-55c052c8-62c3-11e8-9a39-910733a0f8e8.jpg)

**Comment by cronokirby** [comment]
This can be reopened if further interest arises
