### ISSUE TITLE
Dependency on old httpoison version

### ISSUE THREAD

**Issue by Kovus** [cronokirby/alchemy#68]
Ran into an issue trying to use Alchemy with another library I was building that depended on HTTPoison > 1.4.

I was able to work around it by forcing my dependencies to use httpoison 1.5, but I do wonder why Alchemy depends on such an old version of httpoison.

**Comment by cronokirby** [comment]
I'm working on this atm

**Comment by cronokirby** [comment]
Should be fixed as of latest version
