### ISSUE TITLE
Change prefix

### ISSUE THREAD

**Issue by rikusen0335** [cronokirby/alchemy#69]
I want to change prefix like `-ping`, is this can do?
Or may I miss the function?

**Comment by cronokirby** [comment]
Yeah, you can do `Cogs.set_prefix("-")` to set the prefix to "-" this also works with any arbitrary string.

See https://hexdocs.pm/discord_alchemy/Alchemy.Cogs.html#set_prefix/1 for more info :)

**Comment by rikusen0335** [comment]
Thanks. That's helpful for me!
