### ISSUE TITLE
Private_message channel cache is always empty

### ISSUE THREAD

**Issue by OvermindDL1** [cronokirby/alchemy#86]
Attempting to run `Alchemy.Cache.private_channel/1` with a private channel ID or a `user: "..."` ID returns nothing.  Running `Alchemy.Cache.search(:private_channels, fn _ -> true end)` also always returns `[]` even though there are multiple private conversations open with the bot.

**Comment by OvermindDL1** [comment]
Also, not able to use `Alchemy.Cache.member` to get member information from a private message and member ID.

**Comment by jaspinegz** [comment]
From what I remember, the private channel cache is not properly updated (read: used at all). I don't think it is updated when the guild is initially added via `GUILD_CREATE`, and event handlers depend on a property of name `is_private` being true to consider it a private channel, which does not exist in the spec (private channels will never be treated as private).

**Comment by jaspinegz** [comment]
This may now be resolved as per the recent commit #99

**Comment by OvermindDL1** [comment]
Oh nice, thank's for the update, I'll try it out.  :-)
