### ISSUE TITLE
Message-less attachments not coming through

### ISSUE THREAD

**Issue by OvermindDL1** [cronokirby/alchemy#89]
When someone sends a, say, image attachment with a message it comes through fine with the attachment and all, but if the attachment is sent without any text in the message on discord then the bot receives nothing.  This same unchanged code was working fine for this case just a few weeks ago, and it stopped working in this specific case in the past few weeks, thus discord probably changed something.  Need an update to get messages working again.

I'm currently using 0.6.4 (which is at this time, currently the latest version on hex.pm).

**Comment by cronokirby** [comment]
hmm, I wonder if they documented the change

**Comment by OvermindDL1** [comment]
I'm wondering if anyone can replicate it actually, it's entirely possible that my rather unusual setup could be at fault but I've tried logging everything I can do no avail...

**Comment by OvermindDL1** [comment]
Still unsure, but I'm more sure that the issue is in my code, closing this.  I'll reopen if issues.  ^.^;
